Diff should be fixed for easier merging
bokulich-lab/q2-coordinates pull request #16
Opened 2020-12-16 19:21 UTC by zoechallacombe

I am in the middle of finals and my brain is a little scattered, so I may have missed something. Let me know if I did.

2020-12-23 13:00 UTC, adamovanja requested changes
hi @zoechallacombe, thank you for your work. I added a few minor comments to your code. Would be great if you could tackle them and finally rename the PR to what is contained within - something like you had before along the lines of "Fixed node length issue, updated test and readme".
I hope your finals went well :).

2020-12-23 13:00 UTC, adamovanja commented on README.md
>  1. using q2-coordinates draw map to disply the sample positions and color code them by respective quadrant (i.e: set the "column" parameter to the split-depth you want to look at)
above L160: minor spelling mistake "inclued" -> "include"

2020-12-23 13:00 UTC, adamovanja commented on README.md
>  1. using q2-coordinates draw map to disply the sample positions and color code them by respective quadrant (i.e: set the "column" parameter to the split-depth you want to look at)
minor spelling mistake: "disply" -> "display"

2020-12-23 13:00 UTC, adamovanja commented on README.md
> +```
for completeness, it would be great if you could mention before that a prerequisite for this command to work is to [install empress](https://library.qiime2.org/plugins/empress/32/)

2020-12-23 13:00 UTC, adamovanja commented on README.md
> +    --m-feature-metadata-file q2_coordinates/tests/data/chardonnay_sample_metadata.txt \
so all examples from the readme above assume that the working directory is `q2-coordinates/q2-coordinates/tests/data` (see L 50). Could you therefore adjust the path of the metadata-file in the quadtree example command beforehand and the metadata as well as the input file here respectively?

2020-12-23 13:12 UTC, nbokulich commented
fixes #13 

@zoechallacombe for the sake of posterity, could you please also add a comment line above the code block you added, just so future developers know why arbitrary branch lengths are being defined? Thanks!

2021-01-06 19:50 UTC, zoechallacombe commented
Because it is now 2021, the lint check breaks due to copyright date discrepancy. It seems a little bit out of my scope to fix, but everything else should be working fine.

2021-01-07 15:58 UTC, adamovanja commented
hi @zoechallacombe, thank you for the further changes. I believe the copyright template issue should be easily fixable by replacing all`2020` to `2021` in the complete repos. would you mind trying that?

2021-01-10 07:59 UTC, nbokulich commented
happy new year and no worries @zoechallacombe , I updated the copyright years here: https://github.com/bokulich-lab/q2-coordinates/pull/17

Please merge the master branch into `fixing_diff` to update and commit those changes so the rest of the unit tests can run. Thanks!

2021-01-10 08:09 UTC, nbokulich requested changes
this is looking great, thanks @zoechallacombe ! I just have some additional minor changes to request.

2021-01-10 08:09 UTC, nbokulich commented on README.md
> +using qiime2 cli
this line should not be in the code block, right?

2021-01-10 08:09 UTC, nbokulich commented on README.md
> +1. using q2-coordinates draw map to display the sample positions and color code them by respective quadrant (i.e: set the "column" parameter to the split-depth you want to look at)
"using q2-coordinates draw map" --> "using `q2-coordinates draw-map` or `draw-interactive-map`"

"by respective quadrant" --> "by their respective quadrants"

2021-01-10 08:09 UTC, nbokulich commented on README.md
> +Quadtrees can easily be visualized using a mix of python and other existing qiime2 plugins. Some ideas include:
you give some purely Q2 examples including q2-coordinates, so I recommend just saying something along the lines of:

" Quadtrees can easily be integrated into downstream analyses with q2-coordinates and other QIIME 2 plugins, and visualized using other qiime2 plugins (e.g., q2-empress). Some ideas include:"

2021-01-10 08:09 UTC, nbokulich commented on README.md
> +1. using q2-coordinates draw map to display the sample positions and color code them by respective quadrant (i.e: set the "column" parameter to the split-depth you want to look at)
instead of the parenthesis, it might just be simpler to give an example command here using the chardonnay dataset.

2021-02-02 13:14 UTC, adamovanja requested changes
thank you @zoechallacombe for the nice changes. I have added some minor comments, as the suggested commands for drawing a map with the quadtrees can be done directly with one QIIME2 CLI command (instead of a detour in python).

2021-02-02 13:14 UTC, adamovanja commented on README.md
> +qiime tools export --input-path test/output_tree.qza --output-path test
creates a NewickDirectoryFormat tree in my case. I believe the input-path should be changed to `output_table.qza`. Otherwise, the file `test/quadtree.tsv` is not created. However, this command is not needed if we use the below suggested QIIME2 CLI command to draw the map.

2021-02-02 13:14 UTC, adamovanja commented on README.md
>      --output-dir test
would be great if you could change the directory name to sth a bit more informative along the lines of `test_quadtree`

2021-02-02 13:14 UTC, adamovanja commented on README.md
> +
I believe this can be done more directly in qiime2 cli (above suggested new folder name `test_quadtree` is already included):
```
qiime coordinates draw-map \
    --m-metadata-file test_quadtree/output_table.qza \
    --m-metadata-file chardonnay_sample_metadata.txt \
    --p-latitude latitude \
    --p-longitude longitude \
    --p-column split-depth-1 \
    --p-discrete \
    --o-visualization test_quadtree/quadtree-map-depth1.qzv
```

Also, I suggest to add a line before this command to highlight that the split-depth of the drawn map can be selected and that the example shows the map with a split-depth of 1.

2021-02-02 13:14 UTC, adamovanja commented on README.md
> +
I think this section of the ReadMe would gain a lot by embedding the resulting visualisation from QIIME2 VIEW into the ReadMe file (as done above in section "Plotting geocoordinates colored by metadata category values" for the `./examples/vineyard-map.jpg` visualisation).

2021-04-09 15:09 UTC, adamovanja commented
hi @zoechallacombe, our discussion went a bit quiet. What's the status of this PR from your side?

2021-08-13 12:15 UTC, merged