[WIP] adding openlayers
bokulich-lab/q2-coordinates pull request #9
Opened 2020-02-27 21:25 UTC by antgonza

2020-11-17 13:36 UTC, adamovanja requested changes
Thanks @antgonza for including this interactive map to q2-coordinates and sorry for the delayed review. Could you add to the `README.md` an example of how to use the new visualiser? Also, it would be great if you could include a test for it in `test_mapper.py`.

2020-11-17 13:36 UTC, adamovanja commented on q2_coordinates/plugin_setup.py
> +                 'missing values are silently dropped.'),
Could you add in the description that this visualizer is interactive? else description is identical to “plot_map”.

2020-11-17 13:36 UTC, adamovanja commented on q2_coordinates/plugin_setup.py
> +        'image': 'Base map image to use for coordinate projection.'},
Variable `image` is not used in this method (see comment in function def above). could you add this functionality or remove the variable from function definition?

2020-11-17 13:36 UTC, adamovanja commented on q2_coordinates/mapper.py
> +             missing_data: str='error'):
could you indent all input variables of this function?

2020-11-17 13:36 UTC, adamovanja commented on q2_coordinates/mapper.py
> +             image: str='StamenTerrain',
Variable 'image' is not used in this function - could you add the functionality of changing the background image or remove it from the function definition?

2020-11-17 13:36 UTC, adamovanja commented on q2_coordinates/mapper.py
> +    lat_min, lat_max = [lon_0, lat_0], [lon_1, lat_1]
Naming of variables (`lat_min` and `lat_max`) might be confusing. Maybe rename to `loc_min` and `loc_max` - as variable contains both lat and lon?

2020-11-17 13:36 UTC, adamovanja commented on q2_coordinates/_utilities.py
> +def save_animated_map(output_dir, lat_min, lat_max, data, column, fig):
fig is not used in this function - could you remove it from the func definition?

2020-11-17 14:03 UTC, antgonza reviewed
@adamovanja, thank you for review.

2020-11-17 14:03 UTC, antgonza commented on q2_coordinates/_utilities.py
> +def save_animated_map(output_dir, lat_min, lat_max, data, column, fig):
Thank you for catching ... perhaps it will be good to add flake8 to this package, right?

2020-11-17 14:03 UTC, antgonza commented on q2_coordinates/mapper.py
> +             image: str='StamenTerrain',
removed

2020-11-17 14:03 UTC, antgonza commented on q2_coordinates/mapper.py
> +             missing_data: str='error'):
Done

2020-11-17 14:03 UTC, antgonza commented on q2_coordinates/mapper.py
> +    lat_min, lat_max = [lon_0, lat_0], [lon_1, lat_1]
👍🏽

2020-11-17 14:03 UTC, antgonza commented on q2_coordinates/plugin_setup.py
> +        'image': 'Base map image to use for coordinate projection.'},
👍🏽

2020-11-17 14:03 UTC, antgonza commented on q2_coordinates/plugin_setup.py
> +                 'missing values are silently dropped.'),
👍🏽

2020-11-17 14:15 UTC, antgonza commented on q2_coordinates/_utilities.py
> +def save_animated_map(output_dir, lat_min, lat_max, data, column, fig):
Ha! This was done already! 😄

2020-11-17 14:43 UTC, adamovanja commented
Thanks @antgonza for the swift changes. If you add a test in `test_mapper.py` and a brief description on how to use the new method in `README.md`, we are ready to merge.

2020-11-18 15:19 UTC, antgonza commented
@adamovanja, do you know what could be going on with the build error? As background the issue is that the folders and downstream files in `q2_coordinates/assets/animated_map/static` are not being copied. Note that I ran into this issue when installing in my local machine as `pip install .` but worked just fine when installing as `pip install -e .`. Now, I can add all those files to `package_data` in the `setup.py` file but just want to confirm that this is the way to go. Thank you!

2020-11-18 15:27 UTC, adamovanja commented
hi @antgonza, yes, I would also replace `'assets/index.html'` with `'assets/*'`in `setup.py`

2020-11-18 15:30 UTC, antgonza commented
Sounds good. Note that using `/*` will not add the subfolders and files and you need either to list all files or [create a small method to do it automatically](https://stackoverflow.com/a/27664856); do you have a preference?

2020-11-18 15:39 UTC, adamovanja commented
no preference. just listing the subfolders seems good enough for now

2020-11-18 16:59 UTC, adamovanja approved these changes

2020-11-18 16:59 UTC, adamovanja commented
hi @antgonza, thank you for contributing. this looks good from my side

2020-11-18 16:59 UTC, merged